### ISSUE TITLE
Waypoints position and rotation are empty from the scene api

### ISSUE THREAD

**Issue by Aadjou** [archilogic-com/3dio-js#114]
Bug report from [SO](https://stackoverflow.com/questions/47882683/waypoints-position-and-rotation-are-empty-from-the-scene-api)

**How to reproduce**
- io3d.scene.getAframeElements api returns the waypoints with position and rotation empty.

**Expected result**
- The position and rotation are imported correctly. 

**Actual result**
- The position and rotation are empty. 
`<a-entity tour-waypoint="TOP VIEW" io3d-uuid="2c0c947b-5135-456d-9626-8c80778b9dd5" position="" rotation="" scale="" visible=""></a-entity>`

**Comment by AVGP** [comment]
Just chiming in here, because this coincides with an observation I made.
There's definitely an improvement in here, because I think that looking at the DOM should always reflect the truth* and in this case it doesn't.

However, what I wanted to make y'all aware of is: The DOM itself only supports strings in attributes, i.e. `setAttribute('position', '1 2 3')` is good, but `setAttribute('position', {x: 1, y: 2, z: 3})` *is invalid in vanilla DOM*. In A-Frame *this is fine, tho*, because they overwrite `setAttribute` and `getAttribute` accordingly. For performance reasons this isn't necessarily reflected back to the DOM in string form (as that conversion costs computation cycles), but it *should* work.

I think `getAframeElements` uses the object form when setting the attributes, which I think we might wanna change to the string form, because:

* if someone uses it without having A-Frame ready yet (e.g. because they prepopulate the HTML via 3d.io) they'll run into problems
* if someone uses it to generate code to copy&paste for users, they won't get the attributes visible and thus copy incorrect code
* I guess (correct me if I'm wrong) people will call this relatively sparsely (i.e. not in something like `requestAnimationFrame`) and the hit of creating the strings isn't a problem

I'm happy to take this issue up, @frederic-schwarz, if you wish me to :)

**Comment by frederic-schwarz** [comment]
to-aframe-elements.js currently uses strings for setting attributes
like here 
https://github.com/archilogic-com/3dio-js/blob/master/src/scene/structure/to-aframe-elements.js#L292
or here 
https://github.com/archilogic-com/3dio-js/blob/master/src/scene/structure/to-aframe-elements.js#L175

**Comment by AVGP** [comment]
So it turns out that the data gets returned just fine:

```javascript
  document.querySelector('[tour-waypoint]').getAttribute('position') // returns {x: 1, y: 2, z: 3} etc.
```

You can observe this behaviour in [this glitch](https://shard-cirrus.glitch.me/).

However, we assume you'd want to use the HTML in some way, e.g. use `innerHTML` to send this to a server. In that case, you need to call `element.flushToDom()` before, as documented [here](https://aframe.io/docs/0.7.0/core/entity.html#flushtodom-recursive).

[Here is code demonstrating this](https://vigorous-cornet.glitch.me/).
When you look at the code you get after clicking the button, you'll see that the elements where `flushToDOM` was used show up correctly in the text, but the box that was dynamically created (and is a built-in A-Frame element!) does not.
