### ISSUE TITLE
Implement a-frame lightmap controls

### ISSUE THREAD

**Issue by frederic-schwarz** [archilogic-com/3dio-js#13]
```html
<a-entity base-data3d="key:/file.buffer.data3d" position="0 0 0" material="color: red" lightmap="center: 0.5; intensity: 1.0;">
</a-entity>
```

**Comment by AVGP** [comment]
I've been looking at this with Madlaina this morning and figured out, that the lightmap component is basically a dumb data container that then syncs with the other components (`3dio-data3d` or `3dio-furniture`).

This means that it would have to update the other component upon change and does not have any behaviour on its own:

```javascript
// lightmap component

{
  update: function() {
    if(this.el.components['3dio-data3d']) this.el.components['3dio-data3d'|.update()
    else if(this.el.components['3dio-furniture']) this.el.components['3dio-furniture'|.update()

  }
}

// the other components

{
  update: function() {
    if(this.el.components['data3d-lightmap']) {
      // ... read the attributes & apply to data3d view
    }  
  }
}
```

**Comment by Aadjou** [comment]
<img width="327" alt="screen shot 2017-07-19 at 09 16 39" src="https://user-images.githubusercontent.com/25610447/28355143-0a999ab8-6c63-11e7-981d-da0bf19cbae5.png">

**Comment by tomas-polach** [comment]
i think i am misunderstanding something: does it have to be a custom component? i imagined  lightmaps settings code residing inside data3d and furniture components.
- is it that a component can have only one html attribute?
- if that's the case: should we probably rather nest the lightmap params inside the data3d and furniture params instead of creating a separate component for it?
- the separate component approach is design wise a little bit tricky as it is not generic enough (can't be used in compositions with other components in the community -> dependencies management?)

**Comment by Aadjou** [comment]
I guess we're all on the same page then that it should not be a custom component.
i think during the design phase, this was an oversight
(also because I myself was not fully aware of the a-frame components structure & implementation design)
we're going for a solution like this now:
`  <a-entity io3d-data3d="key:/lighting.gz.data3d.buffer; lightMapIntensity:0.1; lightMapCenter:0.5" position="0 -5 -6" shadow="receive: true"></a-entity>
`

**Comment by tomas-polach** [comment]
@Aadjou exactly my leranings as well! :)
i was not aware of the fact that **every attribute in `a-entity` is per definition one component** -  @AVGP is that correct?

**Comment by AVGP** [comment]
Yes, that's correct.

Each attribute can contain multiple properties (like the HTML style
attribute does, e. g. style="color:red; font-weight: bold")

On 19 Jul 2017 10:50 am, "Tomas Polach" <notifications@github.com> wrote:

@Aadjou <https://github.com/aadjou> exactly my leranings as well! :)
i was not aware of the fact that *every attribute in a-entity is per
definition one component* - @AVGP <https://github.com/avgp> is that correct?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/archilogic-com/3dio-js/issues/13#issuecomment-316317590>,
or mute the thread

**Comment by frederic-schwarz** [comment]
### remarks: 
* `0.0` should be treated as `0.0` and not as `undefined` hence fallback to default
* I would rename `lightMapCenter` to `lightMapExposure`
* `lightMapExposure` seems to behave different than Exposure settings in the Editor -> way softer

### test results from the lightmap controls:
* intensity:0, center: 0.5 **-> same as intensity 1 center 0.5**
![0 0-0 5](https://user-images.githubusercontent.com/7444615/28437492-1b06d3fa-6d9b-11e7-881f-41ae53b6c8f5.png)
* intensity:0.01, center: 0.5
![0 01-0 5](https://user-images.githubusercontent.com/7444615/28437494-1ca86c50-6d9b-11e7-9843-d8a6ad5cea38.png)
* intensity:0.5, center: 0.5
![0 5-0 5](https://user-images.githubusercontent.com/7444615/28437497-1fa46efe-6d9b-11e7-8725-f8dcef4b1daf.png)
* intensity:1, center: 0.5
![1-0 5](https://user-images.githubusercontent.com/7444615/28437502-24a46eb8-6d9b-11e7-82fb-ca3eb2b54a37.png)
* intensity:1.5, center: 0.5
![1 5-0 5](https://user-images.githubusercontent.com/7444615/28437506-28b373d2-6d9b-11e7-9294-8a2b60b8bc1c.png)
* intensity:2, center: 1.0
![2-1](https://user-images.githubusercontent.com/7444615/28438132-5a9491ae-6d9d-11e7-9661-bed0ea110702.png)
* intensity:1, center: 0.0 **-> same as intensity 1 center 0.5**
![1-0 0](https://user-images.githubusercontent.com/7444615/28437553-54b6c6c8-6d9b-11e7-9fbb-02bb3c52586c.png)
* intensity:1, center: 0.01
![1-0 01](https://user-images.githubusercontent.com/7444615/28437559-5785c05c-6d9b-11e7-820c-14a7ab594258.png)
* intensity:1, center: 0.5
![1-0 5](https://user-images.githubusercontent.com/7444615/28437566-5ce61704-6d9b-11e7-85b6-1f4a958fcc31.png)
* intensity:1, center: 1
![1-1](https://user-images.githubusercontent.com/7444615/28437571-6113cfec-6d9b-11e7-9d7c-4a0a1f8c0b23.png)
* intensity:1, center: 1.5
![1-1 5](https://user-images.githubusercontent.com/7444615/28437619-97b04e0e-6d9b-11e7-992d-75e9ce220d0c.png)

### editor comparison 
editor of course has different lighting but that doesn't explain the difference in strength
* intensity:1, exposure: 0
![e3d-1-0](https://user-images.githubusercontent.com/7444615/28438102-3e0e9908-6d9d-11e7-832b-a7cf46a020ef.png)
* intensity:1, exposure: 0.5
![e3d-1-0 5](https://user-images.githubusercontent.com/7444615/28438104-3e11d550-6d9d-11e7-9c5a-e675c3907283.png)
* intensity:2, exposure: 0.5
![e3d-2-1](https://user-images.githubusercontent.com/7444615/28438103-3e0f6bbc-6d9d-11e7-921d-0aeb01e93082.png)

**Comment by Aadjou** [comment]
All the code reviews, discussions and refactoring are taking place in the pull request #16 

Therefore i'm closing this issue again.
@frederic-schwarz your tests will be taken into account, thanks for the input
